### ISSUE TITLE
Wrong inputs when controller is set to no SODC cleaning.

### ISSUE THREAD

**Issue by Chinta03** [lucasteles/InputDisplay#2]
**Description:**
When the controller is set to no SOCD cleaning in order to display on stream the actual inputs on the hitbox controller, the Input Display application does not always show the proper input.

Also a lack of feature to pick which SOCD cleaning to use.

![image](https://github.com/lucasteles/InputDisplay/assets/157050139/8a2cbcfc-8fe2-4c11-baa4-e8a331a1b7d4)

![image](https://github.com/lucasteles/InputDisplay/assets/157050139/0258f818-3f9b-4f79-96b9-940843f43970)

**Prerequisites**
- Own a controller that can be set to no SOCD cleaning mode. (Example: Brooks Universal fighting board fusion)

**Reproduction steps**

1. Plug the controller with no SODC cleaning mode
2. Press the following inputs:
  2.1 Left + right
  2.2 Left + Up + Down

**Actual results:**
Some inputs combo result in the wrong input in the Input Display.

**Expected result:**
Show the right input according to the SOCD cleaning rule.

**Comment by lucasteles** [comment]
Thanks for the feedback.

I just got a leverless stick with UFB, I will add a SOCD cleaning option and fix the display

**Comment by lucasteles** [comment]
@Chinta03 I just fixed it. You can test in the latest release.

> [!NOTE]
> I probably should evolve the view for `SOCD` **Bypass** on multiple opposing inputs. But for now, it is at least showing them correctly.

**Comment by Chinta03** [comment]
Hey @lucasteles,
I just tested your new v0.5.1 build and it's still an issue on my side. See the gif below.

![SODC_issue](https://github.com/lucasteles/InputDisplay/assets/157050139/f55f7081-8dde-4f74-80bd-b92fe5860758)
Side note: Windows controller propreties isn't showing the proper inputs either.

I am using a Universal Fighting Board Fusion, set to Controller (XInput STANDARD GAMEPAD) mode.
From what I read, only XInput mode allow SOCD to be displayed.
![image](https://github.com/lucasteles/InputDisplay/assets/157050139/7d12bd9e-1aff-4a54-84ec-a6f4af8c0240)

SODC in the InputDisplay Config to SOCD: Neutral.
![image](https://github.com/lucasteles/InputDisplay/assets/157050139/a189fe8f-0567-4ddb-8e54-e41b882be56c)

And I am running Windows 10 if this can help.

Cheers!

**Comment by lucasteles** [comment]
@Chinta03 I see. I've tested before with a pad (using a d-pad + analog) to validate the SOCD clean modes. In which mode do you connect the board (which buttons did you hold) on the PC?

The app reads the inputs as Windows does, that's the problem, using my `UFB` I was able to replicate it. 

I need some time to investigate how to bypass this 


UPDATE: 
The inputs are wrong at SDL level `SDL_GameControllerGetButton` is returning the wrong `DPad` buttons (like Windows config)

**Comment by Chinta03** [comment]
For my setup. I'm not using any of the Analog inputs, but only the "DPAD" inputs to press opposing directions.
The input mode is "XInput STANDARD GAMEPAD" mode. I tested with some other modes and not all modes could register opposing directions.

**Comment by lucasteles** [comment]
@Chinta03 how did you set this mode up? I could not find it in [the Brook docs](https://www.brookaccessory.com/products/ufbfusion/index.html). 

Is it any of these? 
<img width="402" alt="image" src="https://github.com/lucasteles/InputDisplay/assets/3037609/a5566f91-05fe-42cd-b2b3-0eba161c52b6">

**Comment by Chinta03** [comment]
@lucasteles That would be the XBOX 360 mode, so connecting the USB while holding 3P.
![image](https://github.com/lucasteles/InputDisplay/assets/157050139/00114be7-b1f0-49b5-8546-6abe3788f21f)
